////////////////////////////////////////////////////////////////////
//
//  FILE: config.cpp
//
//
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <iostream>

#include "sys.h"
#include "types.h"

using namespace std;

bool parse_cfg_file (dev_info& dev)
{
	char cfg_file_path[_MAX_PATH];
	FILE *fp;
	char line[256];
	char pmode[32];

	if (!get_cfg_file ("cdi2dvi.cfg", cfg_file_path))
		return false;
	fp = fopen(cfg_file_path, "r");
	if (fp == NULL)
		return false;
	while (fgets(line, 255, fp)) {
		switch (line[0]) {
		case '%': case ' ': case '\t':case '\n': break; // ignore the comment line
		case 'P': // printer mode
			sscanf(line+1, "%s%d%d", pmode, &dev.dpi_x, &dev.dpi_y);
			if (dev.dpi_y == 0) dev.dpi_y = dev.dpi_x;
			break;
		case 'D': // directory to save fonts generated by cdi2dvi
		
		default:
			cerr << "Unknown configuration  flag, it is skipped\n";
		}
	}
	dev.mode = pmode;
	fclose(fp);
	return true;
}
