/* generated from putex.p by C4P version 2.4.1598 */
#ifndef C4P_HEADER_GUARD_tex
#define C4P_HEADER_GUARD_tex
#include <c4plib.h>
#ifdef __cplusplus
using namespace C4P;
#endif
#ifndef C4PEXTERN
#define C4PEXTERN
#endif
#ifdef __cplusplus
extern "C" {
#endif
typedef C4P_unsigned8 asciicode;
typedef C4P_unsigned8 eightbits;
typedef C4P_text alphafile;
typedef C4P_FILE_STRUCT(eightbits) bytefile;
typedef C4P_signed32 poolpointer;
typedef C4P_signed32 strnumber;
typedef C4P_unsigned8 packedasciicode;
typedef C4P_integer scaled;
typedef C4P_signed32 nonnegativeinteger;
typedef C4P_signed8 smallnumber;
typedef C4P_longreal glueratio;
typedef C4P_unsigned16 quarterword;
typedef C4P_signed32 halfword;
typedef C4P_signed8 twochoices;
typedef C4P_signed8 fourchoices;
typedef struct {
  halfword rh;
  union {
    halfword lh;
    struct {
      quarterword b0;
      quarterword b1;
    } c4p_P0;
  } c4p_P1;
} twohalves;
typedef struct {
  quarterword b0;
  quarterword b1;
  quarterword b2;
  quarterword b3;
} fourquarters;
typedef struct {
  union {
    C4P_integer c4p_int;
    glueratio gr;
    twohalves hh;
    fourquarters qqqq;
  } c4p_P2;
} memoryword;
typedef C4P_FILE_STRUCT(memoryword) wordfile;
typedef C4P_signed8 glueord;
typedef struct {
  C4P_signed16 modefield;
  halfword headfield, tailfield;
  C4P_integer pgfield, mlfield;
  memoryword auxfield;
} liststaterecord;
typedef C4P_signed8 groupcode;
typedef struct {
  quarterword statefield, indexfield;
  halfword startfield, locfield, limitfield, namefield;
} instaterecord;
typedef C4P_signed16 internalfontnumber;
typedef C4P_signed32 fontindex;
typedef C4P_signed16 dviindex;
typedef C4P_signed32 triepointer;
typedef C4P_signed16 hyphpointer;
typedef C4P_integer fixword;
typedef C4P_signed16 internalcfacenumber;
typedef C4P_signed16 internalcfontnumber;
typedef C4P_unsigned8 internalectblnumber;
struct c4pdata {
C4P_integer m_bad;
asciicode m_xord[ 256 ];
char m_xchr[ 256 ];
char m_nameoffile[ 261 ];
C4P_signed16 m_namelength;
asciicode *m_buffer;
C4P_signed32 m_first;
C4P_signed32 m_last;
C4P_signed32 m_maxbufstack;
alphafile m_termin;
alphafile m_termout;
packedasciicode *m_strpool;
poolpointer *m_strstart;
poolpointer m_poolptr;
strnumber m_strptr;
poolpointer m_initpoolptr;
strnumber m_initstrptr;
alphafile m_poolfile;
alphafile m_logfile;
C4P_signed8 m_selector;
C4P_signed8 m_dig[ 23 ];
C4P_integer m_tally;
C4P_signed8 m_termoffset;
C4P_signed8 m_fileoffset;
asciicode *m_trickbuf;
C4P_integer m_trickcount;
C4P_integer m_firstcount;
C4P_signed8 m_interaction;
C4P_boolean m_deletionsallowed;
C4P_boolean m_setboxallowed;
C4P_signed8 m_history;
C4P_signed8 m_errorcount;
strnumber m_helpline[ 6 ];
C4P_signed8 m_helpptr;
C4P_boolean m_useerrhelp;
C4P_integer m_interrupt;
C4P_boolean m_oktointerrupt;
C4P_boolean m_aritherror;
scaled m_remainder;
halfword m_tempptr;
memoryword *m_mem;
halfword m_lomemmax;
halfword m_himemmin;
C4P_integer m_varused, m_dynused;
halfword m_avail;
halfword m_memend;
halfword m_rover;
C4P_integer m_fontinshortdisplay;
C4P_integer m_cfontinshortdisplay;
C4P_integer m_depththreshold;
C4P_integer m_breadthmax;
liststaterecord *m_nest;
C4P_unsigned8 m_nestptr;
C4P_unsigned8 m_maxneststack;
liststaterecord m_curlist;
C4P_signed16 m_shownmode;
C4P_signed8 m_oldsetting;
memoryword m_eqtb[ 315919 ];
quarterword m_xeqlevel[ 863 ];
twohalves m_hash[ 45269 ];
halfword m_hashused;
C4P_boolean m_nonewcontrolsequence;
C4P_integer m_cscount;
memoryword *m_savestack;
C4P_signed32 m_saveptr;
C4P_signed32 m_maxsavestack;
quarterword m_curlevel;
groupcode m_curgroup;
C4P_signed32 m_curboundary;
C4P_integer m_magset;
eightbits m_curcmd;
halfword m_curchr;
halfword m_curcs;
halfword m_curtok;
instaterecord *m_inputstack;
C4P_signed16 m_inputptr;
C4P_signed16 m_maxinstack;
instaterecord m_curinput;
C4P_signed8 m_inopen;
C4P_signed8 m_openparens;
alphafile *m_inputfile;
C4P_integer m_line;
C4P_integer *m_linestack;
strnumber *m_sourcefilenamestack;
strnumber *m_fullsourcefilenamestack;
C4P_signed8 m_scannerstatus;
halfword m_warningindex;
halfword m_defref;
halfword *m_paramstack;
C4P_signed16 m_paramptr;
C4P_integer m_maxparamstack;
C4P_integer m_alignstate;
C4P_signed16 m_baseptr;
halfword m_parloc;
halfword m_partoken;
C4P_boolean m_forceeof;
halfword m_curmark[ 5 ];
C4P_unsigned8 m_longstate;
halfword m_pstack[ 9 ];
C4P_integer m_curval;
C4P_signed8 m_curvallevel;
smallnumber m_radix;
glueord m_curorder;
alphafile m_readfile[ 16 ];
C4P_signed8 m_readopen[ 17 ];
halfword m_condptr;
C4P_signed8 m_iflimit;
smallnumber m_curif;
C4P_integer m_ifline;
C4P_integer m_skipline;
strnumber m_curname;
strnumber m_curarea;
strnumber m_curext;
poolpointer m_areadelimiter;
poolpointer m_extdelimiter;
char m_texformatdefault[ 20 ];
C4P_boolean m_nameinprogress;
strnumber m_jobname;
C4P_boolean m_logopened;
bytefile m_dvifile;
strnumber m_outputfilename;
strnumber m_logname;
bytefile m_tfmfile;
memoryword *m_fontinfo;
fontindex m_fmemptr;
internalfontnumber m_fontptr;
fourquarters *m_fontcheck;
scaled *m_fontsize;
scaled *m_fontdsize;
fontindex *m_fontparams;
strnumber *m_fontname;
strnumber *m_fontarea;
eightbits *m_fontbc;
eightbits *m_fontec;
halfword *m_fontglue;
C4P_boolean *m_fontused;
C4P_integer *m_hyphenchar;
C4P_integer *m_skewchar;
fontindex *m_bcharlabel;
C4P_signed16 *m_fontbchar;
C4P_signed16 *m_fontfalsebchar;
C4P_integer *m_charbase;
C4P_integer *m_widthbase;
C4P_integer *m_heightbase;
C4P_integer *m_depthbase;
C4P_integer *m_italicbase;
C4P_integer *m_ligkernbase;
C4P_integer *m_kernbase;
C4P_integer *m_extenbase;
C4P_integer *m_parambase;
fourquarters m_nullcharacter;
C4P_integer m_totalpages;
scaled m_maxv;
scaled m_maxh;
C4P_integer m_maxpush;
C4P_integer m_lastbop;
C4P_integer m_deadcycles;
C4P_boolean m_doingleaders;
quarterword m_c, m_f;
scaled m_ruleht, m_ruledp, m_rulewd;
halfword m_g;
C4P_integer m_lq, m_lr;
eightbits m_dvibuf[ 8193 ];
dviindex m_halfbuf;
dviindex m_dvilimit;
dviindex m_dviptr;
C4P_integer m_dvioffset;
C4P_integer m_dvigone;
halfword m_downptr, m_rightptr;
scaled m_dvih, m_dviv;
scaled m_curh, m_curv;
internalfontnumber m_dvif;
C4P_integer m_curs;
scaled m_totalstretch[ 4 ], m_totalshrink[ 4 ];
C4P_integer m_lastbadness;
halfword m_adjusttail;
C4P_integer m_packbeginline;
twohalves m_emptyfield;
fourquarters m_nulldelimiter;
halfword m_curmlist;
smallnumber m_curstyle;
smallnumber m_cursize;
scaled m_curmu;
C4P_boolean m_mlistpenalties;
internalfontnumber m_curf;
quarterword m_curc;
fourquarters m_curi;
C4P_integer m_magicoffset;
halfword m_curalign;
halfword m_curspan;
halfword m_curloop;
halfword m_alignptr;
halfword m_curhead, m_curtail;
halfword m_justbox;
halfword m_passive;
halfword m_printednode;
halfword m_passnumber;
scaled m_activewidth[ 6 ];
scaled m_curactivewidth[ 6 ];
scaled m_background[ 6 ];
scaled m_breakwidth[ 6 ];
C4P_boolean m_noshrinkerroryet;
halfword m_curp;
C4P_boolean m_secondpass;
C4P_boolean m_finalpass;
C4P_integer m_threshold;
C4P_integer m_minimaldemerits[ 4 ];
C4P_integer m_minimumdemerits;
halfword m_bestplace[ 4 ];
halfword m_bestplline[ 4 ];
scaled m_discwidth;
halfword m_easyline;
halfword m_lastspecialline;
scaled m_firstwidth;
scaled m_secondwidth;
scaled m_firstindent;
scaled m_secondindent;
halfword m_bestbet;
C4P_integer m_fewestdemerits;
halfword m_bestline;
C4P_integer m_actuallooseness;
C4P_integer m_linediff;
C4P_signed16 m_hc[ 66 ];
smallnumber m_hn;
halfword m_ha, m_hb;
internalfontnumber m_hf;
C4P_signed16 m_hu[ 64 ];
C4P_integer m_hyfchar;
asciicode m_curlang, m_initcurlang;
C4P_integer m_lhyf, m_rhyf, m_initlhyf, m_initrhyf;
halfword m_hyfbchar;
C4P_signed8 m_hyf[ 65 ];
halfword m_initlist;
C4P_boolean m_initlig;
C4P_boolean m_initlft;
smallnumber m_hyphenpassed;
halfword m_curl, m_curr;
halfword m_curq;
halfword m_ligstack;
C4P_boolean m_ligaturepresent;
C4P_boolean m_lfthit, m_rthit;
twohalves *m_trie;
smallnumber *m_hyfdistance;
smallnumber *m_hyfnum;
quarterword *m_hyfnext;
C4P_signed16 m_opstart[ 256 ];
strnumber m_hyphword[ 608 ];
halfword m_hyphlist[ 608 ];
hyphpointer m_hyphcount;
C4P_signed16 *m_trieophash;
quarterword m_trieused[ 256 ];
asciicode *m_trieoplang;
quarterword *m_trieopval;
C4P_signed16 m_trieopptr;
packedasciicode *m_triec;
quarterword *m_trieo;
triepointer *m_triel;
triepointer *m_trier;
triepointer m_trieptr;
triepointer *m_triehash;
C4P_boolean *m_trietaken;
triepointer m_triemin[ 256 ];
triepointer m_triemax;
C4P_boolean m_trienotready;
scaled m_bestheightplusdepth;
halfword m_pagetail;
C4P_signed8 m_pagecontents;
scaled m_pagemaxdepth;
halfword m_bestpagebreak;
C4P_integer m_leastpagecost;
scaled m_bestsize;
scaled m_pagesofar[ 8 ];
halfword m_lastglue;
C4P_integer m_lastpenalty;
scaled m_lastkern;
C4P_integer m_insertpenalties;
C4P_boolean m_outputactive;
internalfontnumber m_mainf;
fourquarters m_maini;
fourquarters m_mainj;
fontindex m_maink;
halfword m_mainp;
C4P_integer m_mains;
halfword m_bchar;
halfword m_falsebchar;
C4P_boolean m_cancelboundary;
C4P_boolean m_insdisc;
halfword m_curbox;
halfword m_aftertoken;
C4P_boolean m_longhelpseen;
strnumber m_formatident;
wordfile m_fmtfile;
C4P_integer m_readyalready;
alphafile m_writefile[ 16 ];
C4P_boolean m_writeopen[ 18 ];
halfword m_writeloc;
c4pjmpbuf m_eotexbuf, m_finbuf;
C4P_integer m_memmin;
C4P_integer m_memmax;
C4P_integer m_membot;
C4P_integer m_memtop;
C4P_integer m_bufsize;
C4P_integer m_errorline;
C4P_integer m_halferrorline;
C4P_integer m_maxprintline;
C4P_integer m_stacksize;
C4P_integer m_maxinopen;
C4P_integer m_fontmax;
C4P_integer m_fontmemsize;
C4P_integer m_paramsize;
C4P_integer m_nestsize;
C4P_integer m_maxstrings;
C4P_integer m_stringvacancies;
C4P_integer m_poolsize;
C4P_integer m_savesize;
C4P_integer m_triesize;
C4P_integer m_trieopsize;
halfword m_specialloc;
halfword m_specialtoken;
C4P_boolean m_quotedfilename;
asciicode m_hibyte, m_lobyte;
quarterword m_dbchar;
C4P_boolean m_expandchar;
eightbits m_doccharset;
C4P_boolean m_charvalflag;
C4P_boolean m_cnumoneflag;
internalcfontnumber m_maincf;
C4P_signed16 m_mathmodesave;
internalcfontnumber m_prevmaincf;
halfword m_preundetglueptr;
halfword m_undetglueptr;
halfword m_cglueptr;
halfword m_cgluespec;
halfword m_pregluecharptr;
halfword m_outertail;
halfword m_hboxtail;
C4P_boolean m_insetbox;
internalcfacenumber m_cfaceptr;
strnumber m_cface[ 257 ];
strnumber m_cfacename[ 257 ];
eightbits m_cfacecharset[ 257 ];
C4P_signed16 m_cfaceweight[ 257 ];
eightbits m_cfacestyle[ 257 ];
fixword m_cfacefwwidth[ 257 ];
fixword m_cfacefwheight[ 257 ];
fixword m_cfacefwdepth[ 257 ];
C4P_integer m_cfacecspwidth[ 257 ];
C4P_integer m_cfacecspshrink[ 257 ];
C4P_integer m_cfacecspstretch[ 257 ];
C4P_integer m_cfacecespwidth[ 257 ];
C4P_integer m_cfacecespshrink[ 257 ];
C4P_integer m_cfacecespstretch[ 257 ];
fixword m_cfacefwdefaultdepth;
internalcfontnumber m_cfontptr;
internalcfacenumber m_cfontface[ 5001 ];
scaled m_cfontdsize[ 5001 ];
scaled m_cfontsize[ 5001 ];
scaled m_cfontwidth[ 5001 ];
scaled m_cfontheight[ 5001 ];
scaled m_cfontdepth[ 5001 ];
halfword m_cfontgluespec[ 5001 ];
halfword m_cfontcegluespec[ 5001 ];
C4P_boolean m_cfontused[ 5001 ];
strnumber m_ectblefacename[ 256 ];
internalectblnumber m_ectblptr;
C4P_integer m_gcspacewidth;
C4P_integer m_gcspaceshrink;
C4P_integer m_gcspacestretch;
C4P_integer m_gcespacewidth;
C4P_integer m_gcespaceshrink;
C4P_integer m_gcespacestretch;
internalcfontnumber m_dvicf;
};
C4PEXTERN struct c4pdata g_PUTeXData;
void initialize (void);
void println (void);
void printchar (asciicode s);
void print (C4P_integer s);
void slowprint (C4P_integer s);
void printnl (strnumber s);
void printesc (strnumber s);
void printthedigs (eightbits k);
void printint (C4P_integer n);
void printcs (C4P_integer p);
void sprintcs (halfword p);
void printfilename (C4P_integer n,  C4P_integer a,  C4P_integer e);
void printsize (C4P_integer s);
void printwritewhatsit (strnumber s,  halfword p);
void printchineseint (C4P_integer n,  C4P_integer digitbase,  C4P_boolean simple,  C4P_boolean formal);
void printsmallchineseint (C4P_integer n,  C4P_integer digitbase,  C4P_boolean simple,  C4P_boolean formal);
void printmediumchineseint (C4P_integer n,  C4P_integer digitbase,  C4P_boolean simple,  C4P_boolean formal);
void printcjkint (C4P_integer n,  C4P_integer digitbase,  C4P_integer sign);
void jumpout (void);
void error (void);
void fatalerror (strnumber s);
void overflow (strnumber s,  C4P_integer n);
void confusion (strnumber s);
void printcstyleerrormessage (strnumber s);
halfword getcatcode (halfword ch);
void splitnumber (C4P_integer n);
void resetcfacecspace (C4P_integer facenum);
void resetcfacecespace (C4P_integer facenum);
C4P_boolean aopenin (alphafile & f);
C4P_boolean aopenout (alphafile & f);
C4P_boolean bopenin (bytefile & f);
C4P_boolean bopenout (bytefile & f);
C4P_boolean wopenin (wordfile & f);
C4P_boolean wopenout (wordfile & f);
void aclose (alphafile & f);
void bclose (bytefile & f);
void wclose (wordfile & f);
C4P_boolean initterminal (void);
strnumber makestring (void);
C4P_boolean streqbuf (strnumber s,  C4P_integer k);
C4P_boolean streqstr (strnumber s,  strnumber t);
C4P_boolean getstringsstarted (void);
void printtwo (C4P_integer n);
void printhex (C4P_integer n);
void printromanint (C4P_integer n);
void printcurrentstring (void);
void terminput (void);
void interror (C4P_integer n);
void normalizeselector (void);
void pauseforinstructions (void);
C4P_integer half (C4P_integer x);
scaled rounddecimals (smallnumber k);
void printscaled (scaled s);
scaled multandadd (C4P_integer n,  scaled x,  scaled y,  scaled maxanswer);
scaled xovern (scaled x,  C4P_integer n);
scaled xnoverd (scaled x,  C4P_integer n,  C4P_integer d);
halfword badness (scaled t,  scaled s);
void showtokenlist (C4P_integer p,  C4P_integer q,  C4P_integer l);
void runaway (void);
halfword getavail (void);
void flushlist (halfword p);
halfword getnode (C4P_integer s);
void freenode (halfword p,  halfword s);
void sortavail (void);
halfword newnullbox (void);
halfword newrule (void);
halfword newligature (quarterword f,  quarterword c,  halfword q);
halfword newligitem (quarterword c);
halfword newdisc (void);
halfword newmath (scaled w,  smallnumber s);
halfword newspec (halfword p);
halfword newparamglue (smallnumber n);
halfword newglue (halfword q);
halfword newskipparam (smallnumber n);
halfword newkern (scaled w);
halfword newpenalty (C4P_integer m);
void shortdisplay (C4P_integer p);
void printfontandchar (C4P_integer p);
void printmark (C4P_integer p);
void printruledimen (scaled d);
void printglue (scaled d,  C4P_integer order,  strnumber s);
void printspec (C4P_integer p,  strnumber s);
void printfamandchar (halfword p);
void printdelimiter (halfword p);
void printsubsidiarydata (halfword p,  asciicode c);
void printstyle (C4P_integer c);
void printskipparam (C4P_integer n);
void shownodelist (C4P_integer p);
void showbox (halfword p);
void deletetokenref (halfword p);
void deleteglueref (halfword p);
void flushnodelist (halfword p);
halfword copynodelist (halfword p);
void printmode (C4P_integer m);
void pushnest (void);
void popnest (void);
void showactivities (void);
void printparam (C4P_integer n);
void fixdateandtime (void);
void begindiagnostic (void);
void enddiagnostic (C4P_boolean blankline);
void printlengthparam (C4P_integer n);
void printcmdchr (quarterword cmd,  halfword chrcode);
void showeqtb (halfword n);
halfword idlookup (C4P_integer j,  C4P_integer l);
void primitive (strnumber s,  quarterword c,  halfword o);
void newsavelevel (groupcode c);
void eqdestroy (memoryword w);
void eqsave (halfword p,  quarterword l);
void eqdefine (halfword p,  quarterword t,  halfword e);
void eqworddefine (halfword p,  C4P_integer w);
void geqdefine (halfword p,  quarterword t,  halfword e);
void geqworddefine (halfword p,  C4P_integer w);
void saveforafter (halfword t);
void restoretrace (halfword p,  strnumber s);
void unsave (void);
void preparemag (void);
void tokenshow (halfword p);
void printmeaning (void);
void showcurcmdchr (void);
void showcontext (void);
void begintokenlist (halfword p,  quarterword t);
void endtokenlist (void);
void backinput (void);
void backerror (void);
void inserror (void);
void beginfilereading (void);
void endfilereading (void);
void clearforerrorprompt (void);
void checkoutervalidity (void);
void getnext (void);
void firmuptheline (void);
void gettoken (void);
void macrocall (void);
void insertrelax (void);
void expand (void);
void getxtoken (void);
void xtoken (void);
void scanleftbrace (void);
void scanoptionalequals (void);
C4P_boolean scankeyword (strnumber s);
void muerror (void);
void scaneightbitint (void);
void scancharnum (void);
void scanfourbitint (void);
void scanfifteenbitint (void);
void scantwentysevenbitint (void);
void scanwcharnum (void);
void scanfontident (void);
void findfontdimen (C4P_boolean writing);
void scansomethinginternal (smallnumber level,  C4P_boolean negative);
void scanint (void);
void scandimen (C4P_boolean mu,  C4P_boolean inf,  C4P_boolean shortcut);
void scanglue (smallnumber level);
halfword scanrulespec (void);
strnumber scanname (void);
halfword strtoks (poolpointer b);
halfword thetoks (void);
void insthetoks (void);
void convtoks (void);
halfword scantoks (C4P_boolean macrodef,  C4P_boolean xpand);
void readtoks (C4P_integer n,  halfword r);
void passtext (void);
void changeiflimit (smallnumber l,  halfword p);
void conditional (void);
void beginname (void);
C4P_boolean morename (asciicode c);
void endname (void);
void packfilename (strnumber n,  strnumber a,  strnumber e);
strnumber makenamestring (void);
strnumber amakenamestring (alphafile & f);
strnumber bmakenamestring (bytefile & f);
strnumber wmakenamestring (wordfile & f);
void scanfilename (void);
void packjobname (strnumber s);
void promptfilename (strnumber s,  strnumber e);
void openlogfile (void);
void startinput (void);
internalfontnumber readfontinfo (halfword u,  strnumber nom,  strnumber aire,  scaled s);
void charwarning (internalfontnumber f,  eightbits c);
halfword newcharacter (internalfontnumber f,  eightbits c);
void writedvi (dviindex a,  dviindex b);
void dviswap (void);
void dvifour (C4P_integer x);
void dvipop (C4P_integer l);
void dvifontdef (internalfontnumber f);
void dvicfontdef (internalcfontnumber f);
void movement (scaled w,  eightbits o);
void prunemovements (C4P_integer l);
void specialout (halfword p);
void writeout (halfword p);
void outwhat (halfword p);
void hlistout (void);
void vlistout (void);
void shipout (halfword p);
void scanspec (groupcode c,  C4P_boolean threecodes);
halfword hpack (halfword p,  scaled w,  smallnumber m);
halfword vpackage (halfword p,  scaled h,  smallnumber m,  scaled l);
void appendtovlist (halfword b);
halfword newnoad (void);
halfword newstyle (smallnumber s);
halfword newchoice (void);
void showinfo (void);
halfword fractionrule (scaled t);
halfword overbar (halfword b,  scaled k,  scaled t);
halfword charbox (internalfontnumber f,  quarterword c);
void stackintobox (halfword b,  internalfontnumber f,  quarterword c);
scaled heightplusdepth (internalfontnumber f,  quarterword c);
halfword vardelimiter (halfword d,  smallnumber s,  scaled v);
halfword rebox (halfword b,  scaled w);
halfword mathglue (halfword g,  scaled m);
void mathkern (halfword p,  scaled m);
void flushmath (void);
halfword cleanbox (halfword p,  smallnumber s);
void fetch (halfword a);
void makeover (halfword q);
void makeunder (halfword q);
void makevcenter (halfword q);
void makeradical (halfword q);
void makemathaccent (halfword q);
void makefraction (halfword q);
scaled makeop (halfword q);
void makeord (halfword q);
void makescripts (halfword q,  scaled delta);
smallnumber makeleftright (halfword q,  smallnumber style,  scaled maxd,  scaled maxh);
void mlisttohlist (void);
void pushalignment (void);
void popalignment (void);
void getpreambletoken (void);
void initalign (void);
void initspan (halfword p);
void initrow (void);
void initcol (void);
C4P_boolean fincol (void);
void finrow (void);
void finalign (void);
void alignpeek (void);
halfword finiteshrink (halfword p);
void trybreak (C4P_integer pi,  smallnumber breaktype);
void postlinebreak (C4P_integer finalwidowpenalty);
smallnumber reconstitute (smallnumber j,  smallnumber n,  halfword bchar,  halfword hchar);
void hyphenate (void);
quarterword newtrieop (smallnumber d,  smallnumber n,  quarterword v);
triepointer trienode (triepointer p);
triepointer compresstrie (triepointer p);
void firstfit (triepointer p);
void triepack (triepointer p);
void triefix (triepointer p);
void newpatterns (void);
void inittrie (void);
void linebreak (C4P_integer finalwidowpenalty);
void newhyphexceptions (void);
halfword prunepagetop (halfword p);
halfword vertbreak (halfword p,  scaled h,  scaled d);
halfword vsplit (eightbits n,  scaled h);
void printtotals (void);
void freezepagespecs (smallnumber s);
void boxerror (eightbits n);
void ensurevbox (eightbits n);
void fireup (halfword c);
void buildpage (void);
void appspace (void);
void insertdollarsign (void);
void youcant (void);
void reportillegalcase (void);
C4P_boolean privileged (void);
C4P_boolean itsallover (void);
void appendglue (void);
void appendkern (void);
void offsave (void);
void extrarightbrace (void);
void normalparagraph (void);
void boxend (C4P_integer boxcontext);
void beginbox (C4P_integer boxcontext);
void scanbox (C4P_integer boxcontext);
void package (smallnumber c);
smallnumber normmin (C4P_integer h);
void newgraf (C4P_boolean indented);
void indentinhmode (void);
void headforvmode (void);
void endgraf (void);
void begininsertoradjust (void);
void makemark (void);
void appendpenalty (void);
void deletelast (void);
void unpackage (void);
void appenditaliccorrection (void);
void appenddiscretionary (void);
void builddiscretionary (void);
void makeaccent (void);
void alignerror (void);
void noalignerror (void);
void omiterror (void);
void doendv (void);
void cserror (void);
void pushmath (groupcode c);
void initmath (void);
void starteqno (void);
void scanmath (halfword p);
void setmathchar (C4P_integer c);
void mathlimitswitch (void);
void scandelimiter (halfword p,  C4P_boolean r);
void mathradical (void);
void mathac (void);
void appendchoices (void);
halfword finmlist (halfword p);
void buildchoices (void);
void subsup (void);
void mathfraction (void);
void mathleftright (void);
void aftermath (void);
void resumeafterdisplay (void);
void setcgluespec (C4P_integer n);
void setcegluespec (C4P_integer n);
strnumber fetchefontface (strnumber efontname);
void getrtoken (void);
void trapzeroglue (void);
void doregistercommand (smallnumber a);
void alteraux (void);
void alterprevgraf (void);
void alterpagesofar (void);
void alterinteger (void);
void alterboxdimen (void);
scaled fwtimessd (fixword x,  scaled z);
internalcfacenumber findcfacenum (strnumber id);
internalcfontnumber checkcfont (internalcfacenumber cfacenum,  scaled size);
internalcfontnumber makecfont (internalcfacenumber cfn,  scaled dsize,  scaled size);
void newfont (smallnumber a);
void newinteraction (void);
void printfixword (fixword s);
void newcface (smallnumber a);
void makecfontid (internalcfontnumber f,  smallnumber a);
internalectblnumber findecnum (strnumber efacename);
void matchecface (smallnumber a);
internalcfacenumber lookupcface (strnumber efontname);
void matchecfont (smallnumber a);
void prefixedcommand (void);
void doassignments (void);
void openorclosein (void);
void issuemessage (void);
void shiftcase (void);
void showwhatever (void);
void storefmtfile (void);
void newwhatsit (smallnumber s,  smallnumber w);
void newwritewhatsit (smallnumber w);
void doextension (void);
void fixlanguage (void);
void insertsrcspecial (void);
void appendsrcspecial (void);
void handlerightbrace (void);
void maincontrol (void);
void giveerrhelp (void);
C4P_boolean openfmtfile (void);
C4P_boolean loadfmtfile (void);
void closefilesandterminate (void);
void finalcleanup (void);
void initprim (void);

#ifdef __cplusplus
extern "C++" void __cdecl RunPUTeX (int argc, const char * * argv);
#endif
#ifdef __cplusplus
}
#endif

#endif
